//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class AppControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    getHello(): Promise<void> {
        let url_ = this.baseUrl + "/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetHello(_response);
        });
    }

    protected processGetHello(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class UsersControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get all users
     * @return Return all users.
     */
    findAll(): Promise<UserResponseModel[]> {
        let url_ = this.baseUrl + "/users";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFindAll(_response);
        });
    }

    protected processFindAll(response: Response): Promise<UserResponseModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(UserResponseModel.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserResponseModel[]>(null as any);
    }

    /**
     * Create a new user
     * @return The user has been successfully created.
     */
    create(body: UserRequestModel): Promise<UserResponseModel> {
        let url_ = this.baseUrl + "/users";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<UserResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = UserResponseModel.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserResponseModel>(null as any);
    }

    /**
     * Search user by email
     * @return Return the user.
     */
    findByEmail(email: string): Promise<UserResponseModel> {
        let url_ = this.baseUrl + "/users/search?";
        if (email === undefined || email === null)
            throw new Error("The parameter 'email' must be defined and cannot be null.");
        else
            url_ += "email=" + encodeURIComponent("" + email) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFindByEmail(_response);
        });
    }

    protected processFindByEmail(response: Response): Promise<UserResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserResponseModel>(null as any);
    }

    /**
     * Get user by id
     * @return Return the user.
     */
    findOne(id: string): Promise<UserResponseModel> {
        let url_ = this.baseUrl + "/users/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFindOne(_response);
        });
    }

    protected processFindOne(response: Response): Promise<UserResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserResponseModel>(null as any);
    }

    /**
     * Update a user
     * @return The user has been successfully updated.
     */
    update(id: string, body: UserUpdateModel): Promise<UserResponseModel> {
        let url_ = this.baseUrl + "/users/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<UserResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserResponseModel>(null as any);
    }
}

export class AuthenticationControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    login(body: LoginRequest): Promise<void> {
        let url_ = this.baseUrl + "/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    validateToken(authorization: string): Promise<void> {
        let url_ = this.baseUrl + "/auth/validate";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Authorization": authorization !== undefined && authorization !== null ? "" + authorization : "",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processValidateToken(_response);
        });
    }

    protected processValidateToken(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    decodeToken(body: DecodeTokenRequest): Promise<void> {
        let url_ = this.baseUrl + "/auth/decode";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDecodeToken(_response);
        });
    }

    protected processDecodeToken(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    refreshToken(): Promise<void> {
        let url_ = this.baseUrl + "/auth/refresh-token";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRefreshToken(_response);
        });
    }

    protected processRefreshToken(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    check(): Promise<void> {
        let url_ = this.baseUrl + "/auth/check";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCheck(_response);
        });
    }

    protected processCheck(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class ProjectsControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get all projects
     * @return Return all projects.
     */
    findAll(): Promise<ProjectsResponseModel[]> {
        let url_ = this.baseUrl + "/projects";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFindAll(_response);
        });
    }

    protected processFindAll(response: Response): Promise<ProjectsResponseModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ProjectsResponseModel.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProjectsResponseModel[]>(null as any);
    }

    /**
     * Create a new project
     * @return The project has been successfully created.
     */
    create(body: ProjectsRequestModel): Promise<ProjectsResponseModel> {
        let url_ = this.baseUrl + "/projects";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<ProjectsResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ProjectsResponseModel.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProjectsResponseModel>(null as any);
    }

    /**
     * Get a project by ID
     * @return Return the project.
     */
    findOne(id: string): Promise<ProjectsResponseModel> {
        let url_ = this.baseUrl + "/projects/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFindOne(_response);
        });
    }

    protected processFindOne(response: Response): Promise<ProjectsResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProjectsResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProjectsResponseModel>(null as any);
    }

    /**
     * Update a project by ID
     * @return The project has been successfully updated.
     */
    update(id: string, body: ProjectsUpdateModel): Promise<ProjectsResponseModel> {
        let url_ = this.baseUrl + "/projects/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<ProjectsResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProjectsResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProjectsResponseModel>(null as any);
    }

    /**
     * Delete a project by ID
     * @return The project has been successfully deleted.
     */
    delete(id: string): Promise<void> {
        let url_ = this.baseUrl + "/projects/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class BotConfigurationsControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get bot configuration by prompt id
     * @return The user has been successfully created.
     */
    getByPromtId(promptId: number): Promise<BotConfigResponse> {
        let url_ = this.baseUrl + "/bot-config/prompt-id/{promptId}";
        if (promptId === undefined || promptId === null)
            throw new Error("The parameter 'promptId' must be defined.");
        url_ = url_.replace("{promptId}", encodeURIComponent("" + promptId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetByPromtId(_response);
        });
    }

    protected processGetByPromtId(response: Response): Promise<BotConfigResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = BotConfigResponse.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BotConfigResponse>(null as any);
    }

    updateOrCreateBotConfig(body: BotConfigRequest): Promise<void> {
        let url_ = this.baseUrl + "/bot-config/update";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateOrCreateBotConfig(_response);
        });
    }

    protected processUpdateOrCreateBotConfig(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    deleteById(): Promise<void> {
        let url_ = this.baseUrl + "/bot-config/delete";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteById(_response);
        });
    }

    protected processDeleteById(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class FileUploadsControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    uploadFile(file: FileParameter | undefined): Promise<void> {
        let url_ = this.baseUrl + "/file-uploads";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (file === null || file === undefined)
            throw new Error("The parameter 'file' cannot be null.");
        else
            content_.append("file", file.data, file.fileName ? file.fileName : "file");

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUploadFile(_response);
        });
    }

    protected processUploadFile(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get all file uploads by prompt ID
     * @return Returns all file uploads for a given prompt ID
     */
    getFileUploadsByPromptId(promptId: string): Promise<FileUploadsResponseModel> {
        let url_ = this.baseUrl + "/file-uploads?";
        if (promptId === undefined || promptId === null)
            throw new Error("The parameter 'promptId' must be defined and cannot be null.");
        else
            url_ += "promptId=" + encodeURIComponent("" + promptId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetFileUploadsByPromptId(_response);
        });
    }

    protected processGetFileUploadsByPromptId(response: Response): Promise<FileUploadsResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FileUploadsResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileUploadsResponseModel>(null as any);
    }

    /**
     * Delete a file upload by ID
     * @return The file upload has been successfully deleted.
     */
    deleteFileUpload(id: string): Promise<void> {
        let url_ = this.baseUrl + "/file-uploads/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteFileUpload(_response);
        });
    }

    protected processDeleteFileUpload(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class PromptsControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Create a new prompt
     * @return The prompt has been successfully created.
     */
    create(body: PromptRequestModel): Promise<PromptResponseModel> {
        let url_ = this.baseUrl + "/prompts";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<PromptResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = PromptResponseModel.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PromptResponseModel>(null as any);
    }

    /**
     * Get all prompts
     * @return Return all prompts.
     */
    findAll(): Promise<PromptResponseModel[]> {
        let url_ = this.baseUrl + "/prompts";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFindAll(_response);
        });
    }

    protected processFindAll(response: Response): Promise<PromptResponseModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PromptResponseModel.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PromptResponseModel[]>(null as any);
    }

    /**
     * Get a prompt by id
     * @return Return the prompt.
     */
    findOne(id: string): Promise<PromptResponseModel> {
        let url_ = this.baseUrl + "/prompts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFindOne(_response);
        });
    }

    protected processFindOne(response: Response): Promise<PromptResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PromptResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PromptResponseModel>(null as any);
    }

    /**
     * Update a prompt
     * @return The prompt has been successfully updated.
     */
    update(id: string): Promise<PromptResponseModel> {
        let url_ = this.baseUrl + "/prompts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "PATCH",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<PromptResponseModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PromptResponseModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PromptResponseModel>(null as any);
    }

    /**
     * Delete a prompt
     * @return The prompt has been successfully deleted.
     */
    remove(id: string): Promise<void> {
        let url_ = this.baseUrl + "/prompts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemove(_response);
        });
    }

    protected processRemove(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class UserResponseModel implements IUserResponseModel {
    /** ID của user */
    id!: number;
    /** Email của user */
    email!: string;
    /** Tên đầy đủ của user */
    fullName!: string;
    /** Avatar của user */
    image!: string;
    /** Trạng thái của user */
    statusId!: string;
    /** Giới tính của user */
    gender!: string;
    /** Ngày sinh của user */
    birth!: Date;
    /** Số điện thoại của user */
    phoneNumber!: string;
    /** Thời gian tạo user */
    createdAt!: Date;
    /** Thời gian cập nhật user */
    updatedAt!: Date;
    projects!: ProjectsResponseModel[];
    /** password của user */
    passwordHash!: string;

    [key: string]: any;

    constructor(data?: IUserResponseModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.projects = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.email = _data["email"];
            this.fullName = _data["fullName"];
            this.image = _data["image"];
            this.statusId = _data["statusId"];
            this.gender = _data["gender"];
            this.birth = _data["birth"] ? new Date(_data["birth"].toString()) : <any>undefined;
            this.phoneNumber = _data["phoneNumber"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : <any>undefined;
            if (Array.isArray(_data["projects"])) {
                this.projects = [] as any;
                for (let item of _data["projects"])
                    this.projects!.push(ProjectsResponseModel.fromJS(item));
            }
            this.passwordHash = _data["passwordHash"];
        }
    }

    static fromJS(data: any): UserResponseModel {
        data = typeof data === 'object' ? data : {};
        let result = new UserResponseModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["email"] = this.email;
        data["fullName"] = this.fullName;
        data["image"] = this.image;
        data["statusId"] = this.statusId;
        data["gender"] = this.gender;
        data["birth"] = this.birth ? this.birth.toISOString() : <any>undefined;
        data["phoneNumber"] = this.phoneNumber;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : <any>undefined;
        if (Array.isArray(this.projects)) {
            data["projects"] = [];
            for (let item of this.projects)
                data["projects"].push(item ? item.toJSON() : <any>undefined);
        }
        data["passwordHash"] = this.passwordHash;
        return data;
    }
}

export interface IUserResponseModel {
    /** ID của user */
    id: number;
    /** Email của user */
    email: string;
    /** Tên đầy đủ của user */
    fullName: string;
    /** Avatar của user */
    image: string;
    /** Trạng thái của user */
    statusId: string;
    /** Giới tính của user */
    gender: string;
    /** Ngày sinh của user */
    birth: Date;
    /** Số điện thoại của user */
    phoneNumber: string;
    /** Thời gian tạo user */
    createdAt: Date;
    /** Thời gian cập nhật user */
    updatedAt: Date;
    projects: ProjectsResponseModel[];
    /** password của user */
    passwordHash: string;

    [key: string]: any;
}

export class ProjectsResponseModel implements IProjectsResponseModel {
    /** The id of the project */
    id!: number;
    /** The name of the project */
    name!: string;
    /** The domain of the project */
    applicationDomain!: string;
    /** The created at of the project */
    createdAt!: Date;
    /** The updated at of the project */
    updatedAt!: Date;
    /** The deleted at of the project */
    deletedAt!: Date;
    users!: UserResponseModel[];

    [key: string]: any;

    constructor(data?: IProjectsResponseModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.users = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
            this.applicationDomain = _data["applicationDomain"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : <any>undefined;
            this.deletedAt = _data["deletedAt"] ? new Date(_data["deletedAt"].toString()) : <any>undefined;
            if (Array.isArray(_data["users"])) {
                this.users = [] as any;
                for (let item of _data["users"])
                    this.users!.push(UserResponseModel.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProjectsResponseModel {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectsResponseModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        data["applicationDomain"] = this.applicationDomain;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : <any>undefined;
        data["deletedAt"] = this.deletedAt ? this.deletedAt.toISOString() : <any>undefined;
        if (Array.isArray(this.users)) {
            data["users"] = [];
            for (let item of this.users)
                data["users"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IProjectsResponseModel {
    /** The id of the project */
    id: number;
    /** The name of the project */
    name: string;
    /** The domain of the project */
    applicationDomain: string;
    /** The created at of the project */
    createdAt: Date;
    /** The updated at of the project */
    updatedAt: Date;
    /** The deleted at of the project */
    deletedAt: Date;
    users: UserResponseModel[];

    [key: string]: any;
}

export class UserRequestModel implements IUserRequestModel {
    /** The username of the user */
    username!: string;
    /** The password hash of the user */
    passwordHash!: string;
    /** The email of the user */
    email!: string;
    /** The gender of the user */
    gender!: number;
    /** The birth of the user */
    birth!: number;
    /** The phone number of the user */
    phone_number!: string;
    /** The image of the user */
    image!: string;
    /** The status id of the user */
    status_id!: number;
    /** The role id of the user */
    role_id!: number;

    [key: string]: any;

    constructor(data?: IUserRequestModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.username = _data["username"];
            this.passwordHash = _data["passwordHash"];
            this.email = _data["email"];
            this.gender = _data["gender"];
            this.birth = _data["birth"];
            this.phone_number = _data["phone_number"];
            this.image = _data["image"];
            this.status_id = _data["status_id"];
            this.role_id = _data["role_id"];
        }
    }

    static fromJS(data: any): UserRequestModel {
        data = typeof data === 'object' ? data : {};
        let result = new UserRequestModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["username"] = this.username;
        data["passwordHash"] = this.passwordHash;
        data["email"] = this.email;
        data["gender"] = this.gender;
        data["birth"] = this.birth;
        data["phone_number"] = this.phone_number;
        data["image"] = this.image;
        data["status_id"] = this.status_id;
        data["role_id"] = this.role_id;
        return data;
    }
}

export interface IUserRequestModel {
    /** The username of the user */
    username: string;
    /** The password hash of the user */
    passwordHash: string;
    /** The email of the user */
    email: string;
    /** The gender of the user */
    gender: number;
    /** The birth of the user */
    birth: number;
    /** The phone number of the user */
    phone_number: string;
    /** The image of the user */
    image: string;
    /** The status id of the user */
    status_id: number;
    /** The role id of the user */
    role_id: number;

    [key: string]: any;
}

export class UserUpdateModel implements IUserUpdateModel {
    /** The username of the user */
    username?: string;
    /** The password hash of the user */
    passwordHash?: string;
    /** The email of the user */
    email?: string;
    /** The gender of the user */
    gender?: number;
    /** The birth of the user */
    birth?: number;
    /** The phone number of the user */
    phone_number?: string;
    /** The image of the user */
    image?: string;
    /** The status id of the user */
    status_id?: number;
    /** The role id of the user */
    role_id?: number;

    [key: string]: any;

    constructor(data?: IUserUpdateModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.username = _data["username"];
            this.passwordHash = _data["passwordHash"];
            this.email = _data["email"];
            this.gender = _data["gender"];
            this.birth = _data["birth"];
            this.phone_number = _data["phone_number"];
            this.image = _data["image"];
            this.status_id = _data["status_id"];
            this.role_id = _data["role_id"];
        }
    }

    static fromJS(data: any): UserUpdateModel {
        data = typeof data === 'object' ? data : {};
        let result = new UserUpdateModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["username"] = this.username;
        data["passwordHash"] = this.passwordHash;
        data["email"] = this.email;
        data["gender"] = this.gender;
        data["birth"] = this.birth;
        data["phone_number"] = this.phone_number;
        data["image"] = this.image;
        data["status_id"] = this.status_id;
        data["role_id"] = this.role_id;
        return data;
    }
}

export interface IUserUpdateModel {
    /** The username of the user */
    username?: string;
    /** The password hash of the user */
    passwordHash?: string;
    /** The email of the user */
    email?: string;
    /** The gender of the user */
    gender?: number;
    /** The birth of the user */
    birth?: number;
    /** The phone number of the user */
    phone_number?: string;
    /** The image of the user */
    image?: string;
    /** The status id of the user */
    status_id?: number;
    /** The role id of the user */
    role_id?: number;

    [key: string]: any;
}

export class LoginRequest implements ILoginRequest {
    email!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginRequest {
    email: string;
    password: string;

    [key: string]: any;
}

export class DecodeTokenRequest implements IDecodeTokenRequest {
    token!: string;

    [key: string]: any;

    constructor(data?: IDecodeTokenRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.token = _data["token"];
        }
    }

    static fromJS(data: any): DecodeTokenRequest {
        data = typeof data === 'object' ? data : {};
        let result = new DecodeTokenRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["token"] = this.token;
        return data;
    }
}

export interface IDecodeTokenRequest {
    token: string;

    [key: string]: any;
}

export class ProjectsRequestModel implements IProjectsRequestModel {
    /** The name of the project */
    projectName!: string;
    /** The domain of the project */
    applicationDomain!: string;
    /** The description of the project */
    description!: string;

    [key: string]: any;

    constructor(data?: IProjectsRequestModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.projectName = _data["projectName"];
            this.applicationDomain = _data["applicationDomain"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): ProjectsRequestModel {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectsRequestModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["projectName"] = this.projectName;
        data["applicationDomain"] = this.applicationDomain;
        data["description"] = this.description;
        return data;
    }
}

export interface IProjectsRequestModel {
    /** The name of the project */
    projectName: string;
    /** The domain of the project */
    applicationDomain: string;
    /** The description of the project */
    description: string;

    [key: string]: any;
}

export class ProjectsUpdateModel implements IProjectsUpdateModel {
    /** The name of the project */
    projectName?: string;
    /** The domain of the project */
    applicationDomain?: string;
    /** The description of the project */
    description?: string;

    [key: string]: any;

    constructor(data?: IProjectsUpdateModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.projectName = _data["projectName"];
            this.applicationDomain = _data["applicationDomain"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): ProjectsUpdateModel {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectsUpdateModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["projectName"] = this.projectName;
        data["applicationDomain"] = this.applicationDomain;
        data["description"] = this.description;
        return data;
    }
}

export interface IProjectsUpdateModel {
    /** The name of the project */
    projectName?: string;
    /** The domain of the project */
    applicationDomain?: string;
    /** The description of the project */
    description?: string;

    [key: string]: any;
}

export class BotConfigResponse implements IBotConfigResponse {
    promptId!: number;
    prompt!: string;
    personality!: string;
    startSuggestions!: string;
    greeting!: string;
    applicationDomains!: string[];
    headerTitle!: string;
    headerTitleColor!: string;
    backgroundColor!: string;
    logo!: string;

    [key: string]: any;

    constructor(data?: IBotConfigResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.applicationDomains = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.promptId = _data["promptId"];
            this.prompt = _data["prompt"];
            this.personality = _data["personality"];
            this.startSuggestions = _data["startSuggestions"];
            this.greeting = _data["greeting"];
            if (Array.isArray(_data["applicationDomains"])) {
                this.applicationDomains = [] as any;
                for (let item of _data["applicationDomains"])
                    this.applicationDomains!.push(item);
            }
            this.headerTitle = _data["headerTitle"];
            this.headerTitleColor = _data["headerTitleColor"];
            this.backgroundColor = _data["backgroundColor"];
            this.logo = _data["logo"];
        }
    }

    static fromJS(data: any): BotConfigResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BotConfigResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["promptId"] = this.promptId;
        data["prompt"] = this.prompt;
        data["personality"] = this.personality;
        data["startSuggestions"] = this.startSuggestions;
        data["greeting"] = this.greeting;
        if (Array.isArray(this.applicationDomains)) {
            data["applicationDomains"] = [];
            for (let item of this.applicationDomains)
                data["applicationDomains"].push(item);
        }
        data["headerTitle"] = this.headerTitle;
        data["headerTitleColor"] = this.headerTitleColor;
        data["backgroundColor"] = this.backgroundColor;
        data["logo"] = this.logo;
        return data;
    }
}

export interface IBotConfigResponse {
    promptId: number;
    prompt: string;
    personality: string;
    startSuggestions: string;
    greeting: string;
    applicationDomains: string[];
    headerTitle: string;
    headerTitleColor: string;
    backgroundColor: string;
    logo: string;

    [key: string]: any;
}

export class BotConfigRequest implements IBotConfigRequest {
    promptId!: number;
    prompt!: string;
    personality!: string;
    startSuggestions!: string;
    greeting!: string;
    applicationDomains!: string[];
    headerTitle!: string;
    headerTitleColor!: string;
    backgroundColor!: string;
    logo!: string;

    [key: string]: any;

    constructor(data?: IBotConfigRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.applicationDomains = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.promptId = _data["promptId"];
            this.prompt = _data["prompt"];
            this.personality = _data["personality"];
            this.startSuggestions = _data["startSuggestions"];
            this.greeting = _data["greeting"];
            if (Array.isArray(_data["applicationDomains"])) {
                this.applicationDomains = [] as any;
                for (let item of _data["applicationDomains"])
                    this.applicationDomains!.push(item);
            }
            this.headerTitle = _data["headerTitle"];
            this.headerTitleColor = _data["headerTitleColor"];
            this.backgroundColor = _data["backgroundColor"];
            this.logo = _data["logo"];
        }
    }

    static fromJS(data: any): BotConfigRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BotConfigRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["promptId"] = this.promptId;
        data["prompt"] = this.prompt;
        data["personality"] = this.personality;
        data["startSuggestions"] = this.startSuggestions;
        data["greeting"] = this.greeting;
        if (Array.isArray(this.applicationDomains)) {
            data["applicationDomains"] = [];
            for (let item of this.applicationDomains)
                data["applicationDomains"].push(item);
        }
        data["headerTitle"] = this.headerTitle;
        data["headerTitleColor"] = this.headerTitleColor;
        data["backgroundColor"] = this.backgroundColor;
        data["logo"] = this.logo;
        return data;
    }
}

export interface IBotConfigRequest {
    promptId: number;
    prompt: string;
    personality: string;
    startSuggestions: string;
    greeting: string;
    applicationDomains: string[];
    headerTitle: string;
    headerTitleColor: string;
    backgroundColor: string;
    logo: string;

    [key: string]: any;
}

export class FileUploadsResponseModel implements IFileUploadsResponseModel {
    /** The id of the file upload */
    id!: number;
    /** The id of the prompt */
    promptId!: number;
    /** The name of the file upload */
    fileName!: string;
    /** The size of the file upload */
    fileSize!: number;
    /** The status of the file upload */
    status!: string;
    /** The created at of the file upload */
    createdAt!: string;
    /** The updated at of the file upload */
    updatedAt!: string;

    [key: string]: any;

    constructor(data?: IFileUploadsResponseModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.promptId = _data["promptId"];
            this.fileName = _data["fileName"];
            this.fileSize = _data["fileSize"];
            this.status = _data["status"];
            this.createdAt = _data["createdAt"];
            this.updatedAt = _data["updatedAt"];
        }
    }

    static fromJS(data: any): FileUploadsResponseModel {
        data = typeof data === 'object' ? data : {};
        let result = new FileUploadsResponseModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["promptId"] = this.promptId;
        data["fileName"] = this.fileName;
        data["fileSize"] = this.fileSize;
        data["status"] = this.status;
        data["createdAt"] = this.createdAt;
        data["updatedAt"] = this.updatedAt;
        return data;
    }
}

export interface IFileUploadsResponseModel {
    /** The id of the file upload */
    id: number;
    /** The id of the prompt */
    promptId: number;
    /** The name of the file upload */
    fileName: string;
    /** The size of the file upload */
    fileSize: number;
    /** The status of the file upload */
    status: string;
    /** The created at of the file upload */
    createdAt: string;
    /** The updated at of the file upload */
    updatedAt: string;

    [key: string]: any;
}

export class PromptRequestModel implements IPromptRequestModel {
    /** The name of the prompt */
    promptName!: string;
    /** The project id of the prompt */
    projectId!: number;
    /** The status of the prompt */
    promptStatus!: number;

    [key: string]: any;

    constructor(data?: IPromptRequestModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.promptName = _data["promptName"];
            this.projectId = _data["projectId"];
            this.promptStatus = _data["promptStatus"];
        }
    }

    static fromJS(data: any): PromptRequestModel {
        data = typeof data === 'object' ? data : {};
        let result = new PromptRequestModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["promptName"] = this.promptName;
        data["projectId"] = this.projectId;
        data["promptStatus"] = this.promptStatus;
        return data;
    }
}

export interface IPromptRequestModel {
    /** The name of the prompt */
    promptName: string;
    /** The project id of the prompt */
    projectId: number;
    /** The status of the prompt */
    promptStatus: number;

    [key: string]: any;
}

export class PromptResponseModel implements IPromptResponseModel {
    /** The id of the prompt */
    id!: number;
    /** The name of the prompt */
    name!: string;
    /** The id of the project */
    projectId!: number;
    /** The status of the prompt */
    status!: number;
    /** The created at of the prompt */
    createdAt!: Date;
    /** The updated at of the prompt */
    updatedAt!: Date;
    /** The deleted at of the prompt */
    deletedAt!: Date;
    project!: ProjectsResponseModel[];

    [key: string]: any;

    constructor(data?: IPromptResponseModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.project = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
            this.projectId = _data["projectId"];
            this.status = _data["status"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : <any>undefined;
            this.deletedAt = _data["deletedAt"] ? new Date(_data["deletedAt"].toString()) : <any>undefined;
            if (Array.isArray(_data["project"])) {
                this.project = [] as any;
                for (let item of _data["project"])
                    this.project!.push(ProjectsResponseModel.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PromptResponseModel {
        data = typeof data === 'object' ? data : {};
        let result = new PromptResponseModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        data["projectId"] = this.projectId;
        data["status"] = this.status;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : <any>undefined;
        data["deletedAt"] = this.deletedAt ? this.deletedAt.toISOString() : <any>undefined;
        if (Array.isArray(this.project)) {
            data["project"] = [];
            for (let item of this.project)
                data["project"].push(item ? item.toJSON() : <any>undefined);
        }
        return data;
    }
}

export interface IPromptResponseModel {
    /** The id of the prompt */
    id: number;
    /** The name of the prompt */
    name: string;
    /** The id of the project */
    projectId: number;
    /** The status of the prompt */
    status: number;
    /** The created at of the prompt */
    createdAt: Date;
    /** The updated at of the prompt */
    updatedAt: Date;
    /** The deleted at of the prompt */
    deletedAt: Date;
    project: ProjectsResponseModel[];

    [key: string]: any;
}

export interface FileParameter {
    data: any;
    fileName: string;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}